name: Build Docker Image from main

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/flashcard-app:latest    
    - name: Push Docker Image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flashcard-app:latest
